# Generated by Django 5.2.6 on 2025-09-29 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_PANNE', 'En Panne'), ('MAINTENANCE', 'En Maintenance')], default='DISPONIBLE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MatierePremiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('designation', models.CharField(max_length=255)),
                ('quantite_stock', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('unite_mesure', models.CharField(default='unité', max_length=20)),
                ('seuil_alerte', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Operateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('cout_horaire', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='OrdreFabrication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_of', models.CharField(max_length=50, unique=True)),
                ('titre', models.CharField(max_length=255)),
                ('quantite_a_produire', models.IntegerField(default=1)),
                ('statut', models.CharField(choices=[('PLANIFIE', 'Planifié'), ('PRODUCTION', 'En Production'), ('TERMINE', 'Terminé')], default='PLANIFIE', max_length=20)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_debut_prevu', models.DateField(blank=True, null=True)),
                ('date_fin_prevue', models.DateField(blank=True, null=True)),
                ('plan_pdf', models.FileField(blank=True, null=True, upload_to='plans/')),
            ],
        ),
        migrations.CreateModel(
            name='PosteDeTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Cutting, Bending, Quality Inspection', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatiereRequise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_necessaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suivi_production.matierepremiere')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('A_FAIRE', 'À Faire'), ('EN_COURS', 'En Cours'), ('TERMINEE', 'Terminée')], default='A_FAIRE', max_length=20, verbose_name="Statut de l'Opération")),
                ('quantite_entree', models.IntegerField(default=0)),
                ('type_operation', models.CharField(choices=[('PRODUCTION', 'Activité de Production'), ('CONSOMMATION', 'Consommation Matière (Input)'), ('QUALITE', 'Contrôle Qualité'), ('LOGISTIQUE', 'Approvisionnement (Supply)')], default='PRODUCTION', max_length=20, verbose_name="Type d'élément")),
                ('titre', models.CharField(help_text="Description spécifique, ex: 'Coupe du tube principal'", max_length=255)),
                ('instructions', models.JSONField(blank=True, help_text='Données structurées des instructions.', null=True)),
                ('numero_phase', models.IntegerField()),
                ('temps_prevu_minutes', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('machine_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='suivi_production.machine')),
                ('matieres_requises', models.ManyToManyField(related_name='operations', through='suivi_production.MatiereRequise', to='suivi_production.matierepremiere')),
                ('ordre_fabrication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='suivi_production.ordrefabrication')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='suivi_production.postedetravail')),
            ],
            options={
                'ordering': ['numero_phase'],
                'unique_together': {('ordre_fabrication', 'numero_phase')},
            },
        ),
        migrations.AddField(
            model_name='matiererequise',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suivi_production.operation'),
        ),
        migrations.CreateModel(
            name='Pointage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_debut', models.DateTimeField()),
                ('heure_fin', models.DateTimeField(blank=True, null=True)),
                ('quantite_fabriquee', models.IntegerField(default=0)),
                ('quantite_rebut', models.IntegerField(default=0)),
                ('quantite_prise_en_charge', models.IntegerField(default=0)),
                ('operateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pointages', to='suivi_production.operateur')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointages', to='suivi_production.operation')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('MANAGER', 'Manager'), ('POSTE', 'Poste de Travail')], default='POSTE', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='matiererequise',
            unique_together={('operation', 'matiere')},
        ),
    ]
