# Generated by Django 5.2.6 on 2025-09-30 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi_production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anomalie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Description du problème rencontré.')),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('OUVERTE', 'Ouverte'), ('RESOLUE', 'Résolue')], default='OUVERTE', max_length=20)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('operateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='suivi_production.operateur')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='suivi_production.operation')),
                ('resolu_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalies_resolues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
