# Generated by Django 5.2.6 on 2025-09-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi_production', '0002_anomalie'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='quantite_derniere_passe',
            field=models.IntegerField(default=0, help_text='Stocke la qté bonne de la dernière session (prod ou retouche)'),
        ),
    ]
