# Generated by Django 5.2.6 on 2025-09-30 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suivi_production', '0003_operation_quantite_derniere_passe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='quantite_derniere_passe',
        ),
    ]
