# Generated by Django 5.2.6 on 2025-09-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi_production', '0004_remove_operation_quantite_derniere_passe'),
    ]

    operations = [
        migrations.AddField(
            model_name='operateur',
            name='postes_qualifies',
            field=models.ManyToManyField(blank=True, related_name='operateurs', to='suivi_production.postedetravail'),
        ),
    ]
