# Generated by Django 5.2.6 on 2025-10-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi_production', '0005_operateur_postes_qualifies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordrefabrication',
            name='statut',
            field=models.CharField(choices=[('PLANIFIE', 'Planifié'), ('PRODUCTION', 'En Production'), ('TERMINE', 'Terminé'), ('ARCHIVE', 'Archivé')], default='PLANIFIE', max_length=20),
        ),
    ]
