# Generated by Django 5.2.6 on 2025-10-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi_production', '0006_alter_ordrefabrication_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordrefabrication',
            name='date_premiere_finalisation',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
