# Generated by Django 5.2.6 on 2025-10-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi_production', '0007_ordrefabrication_date_premiere_finalisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False, unique=True)),
                ('pieces_fabriquees', models.IntegerField(default=0)),
                ('pieces_rebut', models.IntegerField(default=0)),
                ('taux_rebut', models.FloatField(default=0.0)),
                ('operateurs_actifs', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
