# Generated by Django 5.2.6 on 2025-10-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi_production', '0008_dailyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalie',
            name='masquee_dashboard',
            field=models.BooleanField(default=False),
        ),
    ]
