# Generated by Django 5.2.6 on 2025-10-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi_production', '0009_anomalie_masquee_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='matieres_requises_json',
            field=models.JSONField(blank=True, help_text='Stockage temporaire des matières pour le formset.', null=True),
        ),
    ]
